# Generated by Django 5.0.6 on 2024-06-05 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traducoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_br', models.TextField()),
                ('en_gb', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos.tipos')),
            ],
        ),
    ]
