# Generated by Django 5.0.6 on 2024-06-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traducoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traducoes',
            name='en_gb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
